SELECT * FROM Payment WHERE type_id = 4;

SELECT MARK.* FROM MARK LEFT JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID WHERE NAME = 'Art';

SELECT STUDENT.* FROM STUDENT LEFT JOIN PAYMENT ON STUDENT.ID = PAYMENT.STUDENT_ID LEFT JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME = 'WEEKLY';

SELECT STUDENT.* FROM STUDENT LEFT JOIN MARK ON STUDENT.ID = MARK.STUDENT_ID LEFT JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID WHERE SUBJECT.NAME = 'Math';
