DELETE FROM STUDENT WHERE ID IN (SELECT DISTINCT MARK.STUDENT_ID FROM MARK JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID WHERE SUBJECT.GRADE > 4);
DELETE FROM STUDENT WHERE ID IN (SELECT DISTINCT MARK.STUDENT_ID FROM MARK WHERE MARK < 4);
DELETE FROM PAYMENTTYPE WHERE NAME = 'Daily';
DELETE FROM MARK WHERE MARK < 7;




