SELECT * FROM PAYMENT WHERE AMOUNT>=500;

SELECT * FROM STUDENT  WHERE BIRTHDAY < DATEADD(year, -20,'2000-10-10');

SELECT * FROM STUDENT  WHERE GROUPNUMBER = 10 AND BIRTHDAY > DATEADD(year, -20,'2000-10-10');

SELECT * FROM STUDENT WHERE NAME = 'Mike' OR GROUPNUMBER = 4 OR GROUPNUMBER = 5 OR GROUPNUMBER = 6;

SELECT * FROM PAYMENT WHERE PAYMENT_DATE > DATEADD(month, -8,'2000-10-10');

SELECT * FROM STUDENT WHERE NAME LIKE 'A%';

SELECT * FROM STUDENT WHERE (NAME = 'Roxi' AND GROUPNUMBER = 4) OR (NAME = 'Tallie' AND GROUPNUMBER = 9);