ALTER TABLE student
MODIFY birthday DATE NOT NULL;

ALTER TABLE mark
MODIFY mark INT CHECK (mark BETWEEN 1 AND 10) NOT NULL,
MODIFY student_id BIGINT NOT NULL,
MODIFY subject_id BIGINT NOT NULL;

ALTER TABLE subject
MODIFY grade INT CHECK (grade BETWEEN 1 AND 5) NOT NULL;

ALTER TABLE paymenttype
ADD CONSTRAINT unique_name UNIQUE (name);

ALTER TABLE payment
MODIFY type_id BIGINT NOT NULL,
MODIFY amount DECIMAL(10,2) NOT NULL,
MODIFY payment_date DATETIME NOT NULL;