SELECT SUBJECT.* FROM SUBJECT RIGHT JOIN (SELECT SUBJECT_ID, AVG(MARK) AS mark_avg FROM MARK GROUP BY SUBJECT_ID HAVING mark_avg >
(SELECT AVG(MARK) FROM MARK)) ON SUBJECT.ID = SUBJECT_ID;

SELECT STUDENT.* FROM STUDENT RIGHT JOIN (SELECT STUDENT_ID, SUM(AMOUNT) AS amount_sum FROM PAYMENT GROUP BY STUDENT_ID HAVING amount_sum <
(SELECT AVG(AMOUNT) FROM PAYMENT)) ON STUDENT.ID = STUDENT_ID;



